name: Deploy Azure Infra (Service Principal Auth)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure using Service Principal
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Verify Azure login
        run: az account show

      - name: Deploy Bicep/ARM template
        run: |
          az group create --name myResourceGroup --location eastus
          az deployment group create \
            --resource-group myResourceGroup \
            --template-file infra.yaml \
            --parameters @parameters.json

      - name: Logout
        run: az logout
