name: Deploy Azure Infra (Service Principal Auth)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Verify Azure login
        run: az account show

      - name: Deploy Bicep/ARM template
        run: |
          az group create --name myResourceGroup --location eastus
          az deployment group create \
            --resource-group myResourceGroup \
            --template-file infra.json \
            --parameters @parameters.json

      - name: Logout
        run: az logout
